
public class NotasIMPORTANTE {

	//TODO COLOQUEM AS ANOTAÇÕES DO QUE FALTA SER FEITO POR VOCÊS,
	//PRA NÃO ESQUERCERMOS NENHUM CÓDIGO!!!!
	
	//Classe de Log in
	//Atribuir senha aos usuários
	
	//MOSTRAR SEUS PEDIDOS.
	//NÃO MOSTRAR PEDIDOS DE OUTROS CLIENTES.
	//ALTERAR SEU PRÓPRIO PEDIDO. NÃO DE TERCEIROS ==>> O PROFESSOR FALOU PRA GERIR ISSO NOS CONTROLADORES
	//ADM PODE ALTERAR TDS PEDIDOS.
	//MESMA COISA PROS DEMAIS MÉTODOS

	//CRIAR METODO QUE REMOVE INGREDIENTES NA CLASSE DE PRODUTO.
	
	/*DUVIDAS PARA NAO ESQUECER DE PERGUNTAR
	 *	INTEIRO MUITO GRANDE DÁ ERRO. UTILIZAR LONG???
	 *	COMO MANDAR GERAR NUMEROS DE PEDIDO?? O FORMATO? DATA+LETRA INICIAL DO NOME DO CLIENTE+NUMERO RANDOM??? DIA15/06 FICARIA 15062017F+NUMERO RANDOM
	 *	NUMERO PEDIDO VAI TER QUE SER UMA STRING ------- LEMBRAR DE MODIFICAR
	 * 	PESQUISAR JAVADATETIME(É ESSE NOME MESMO??)
	 */
}
