
public class NotasIMPORTANTE {

	//TODO COLOQUEM AS ANOTAÇÕES DO QUE FALTA SER FEITO POR VOCÊS,
	//PRA NÃO ESQUERCERMOS NENHUM CÓDIGO!!!!
	
	//Classe de Log in
	//Atribuir senha aos usuários
	
	//MOSTRAR SEUS PEDIDOS.
	//NÃO MOSTRAR PEDIDOS DE OUTROS CLIENTES.
	//ALTERAR SEU PRÓPRIO PEDIDO. NÃO DE TERCEIROS
	//ADM PODE ALTERAR TDS PEDIDOS.
	//MESMA COISA PROS DEMAIS MÉTODOS
	
}
